version: '3'
services:
  django:
    container_name: django_rest
    build: ./backend
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    expose:
      - "8000"
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  frontend:
    container_name: react
    build: ./frontend
    ports:
      - '3000:3000'
    command: [ "npm", "start" ]
